version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    container_name: "reports-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - reports-network
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "reports-api"
    environment:
      TEST: "test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - reports-network

volumes:
  database_postgres:

networks:
  reports-network:
    driver: bridge