version: "3.8"

services:
  api:
    build: .
    container_name: "reports-api"
    env_file:
      - local/env.sh
    ports:
      - "9000:9000"
    networks:
      - reports-network

networks:
  reports-network:
    driver: bridge
